/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 models/Gdsc.gltf 
*/

import React from "react";
import {
  MeshReflectorMaterial,
  PresentationControls,
  Stage,
  useGLTF,
} from "@react-three/drei";

export function GdscLogo(props) {
  const { nodes, materials } = useGLTF("./models/Gdsc.gltf");
  return (
    <group {...props} dispose={null}>
      <PresentationControls>
        <Stage environment={"city"} intensity={0.5} shadows={false}>
          <mesh
            geometry={nodes.Curve001.geometry}
            material={materials["SVGMat.002"]}
            scale={67.669}
          >
            <mesh
              geometry={nodes.Curve.geometry}
              material={materials["SVGMat.001"]}
            />
            <mesh
              geometry={nodes.Curve002.geometry}
              material={materials["SVGMat.003"]}
            />
            <mesh
              geometry={nodes.Curve003.geometry}
              material={materials["SVGMat.004"]}
            />
          </mesh>
        </Stage>
        <mesh>
          <planeGeometry args={[170, 170]} />
          <MeshReflectorMaterial
            blur={[300, 100]}
            resolution={2048}
            mixBlur={1}
            mixStrength={40}
            roughness={1}
            depthScale={1.2}
            minDepthThreshold={0.4}
            maxDepthThreshold={1.4}
            color={"#101010"}
            metalness={0.5}
          />
        </mesh>
      </PresentationControls>
    </group>
  );
}

useGLTF.preload("./models/Gdsc.gltf");
