/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 models/mouse.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mice(props) {
  const { nodes, materials } = useGLTF("./models/mouse.gltf");
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={1} />
      <pointLight intensity={7} position={[0.5, 2, 1]} />
      <group
        scale={105.287}
        position={[0, 0, 0]}
        rotation={[-Math.PI / -7, 2.5, 0]}
      >
        <mesh
          geometry={nodes.MouseThermaltakeBlack.geometry}
          material={materials["Material.003"]}
          position={[0, 0.011, -0.02]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.025, 0.019, 0.019]}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack001.geometry}
          material={materials["Material.008"]}
          position={[-0.011, 0.015, 0.009]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack002.geometry}
          material={materials["Material.004"]}
          position={[-0.015, 0.011, -0.006]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <group
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        >
          <mesh
            geometry={nodes.MouseThermaltakeBlack003_1.geometry}
            material={materials["main body"]}
          />
          <mesh
            geometry={nodes.MouseThermaltakeBlack003_2.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            geometry={nodes.MouseThermaltakeBlack003_3.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.MouseThermaltakeBlack003_4.geometry}
            material={materials["Material.014"]}
          />
        </group>
        <mesh
          geometry={nodes.MouseThermaltakeBlack004.geometry}
          material={materials["Material.003"]}
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack005.geometry}
          material={materials["Material.016"]}
          position={[0.001, 0, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack007.geometry}
          material={materials["Material.003"]}
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack008.geometry}
          material={materials["main body.001"]}
          position={[0.002, 0.011, -0.02]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack009.geometry}
          material={materials["main body"]}
          position={[0.001, 0.007, 0.002]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack010.geometry}
          material={materials["Material.009"]}
          position={[-0.013, 0.014, 0.004]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack011.geometry}
          material={materials["main body"]}
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack012.geometry}
          material={materials["Material.001"]}
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack013.geometry}
          material={materials["Material.001"]}
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <mesh
          geometry={nodes.MouseThermaltakeBlack014.geometry}
          material={materials["Material.002"]}
          position={[0, 0.011, -0.02]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        />
        <group
          position={[-0.004, 0.008, -0.008]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.018}
        >
          <mesh
            geometry={nodes.MouseThermaltakeBlack015_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.MouseThermaltakeBlack015_2.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.MouseThermaltakeBlack015_3.geometry}
            material={materials["Material.012"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/mouse.gltf");
