/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 models/robo.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Robo(props) {
  const { nodes, materials } = useGLTF('./models/robo.gltf')
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={4} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Blue_Robot} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Orange_Robot} />
      <mesh geometry={nodes.Other_Things.geometry} material={materials.Blue_Robot} position={[-0.232, 1.512, 0.174]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Text.geometry} material={materials.Orange_Robot} position={[0.387, 2.076, 0.321]} rotation={[2.037, 0.269, 0.461]} scale={[0.182, 0.192, 0.208]} />
      <mesh geometry={nodes.Text001.geometry} material={materials.Orange_Robot} position={[-0.084, 1.567, 0.245]} rotation={[2.104, 0, 0]} scale={[0.153, 0.161, 0.175]} />
      <mesh geometry={nodes.thingy.geometry} material={materials.Orange_Robot_Bright} position={[-0.171, 1.512, 0.174]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('./models/robo.gltf')
