/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Unity/scene.gltf 
Author: AntonioModer (https://sketchfab.com/AntonioModer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unity-logo-3d-mesh-2afd04b26ca64c6b8392f75e217ffdb9
Title: Unity logo 3D mesh
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Unity3D(props) {
  const { nodes, materials } = useGLTF('./models/Unity/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={0.6} position={[0, 3, 1]} />
      <group scale={0.015}>
        <mesh geometry={nodes.Unity_3DLogo_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 3.3, 0, 11.8]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload("./models/Unity/scene.gltf");
