/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\unity.gltf 
*/

import { useGLTF } from '@react-three/drei'

export function Unity3D(props) {
  const { nodes, materials } = useGLTF("./models/unity.gltf");
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={1} position={[0, 1, 4]} />
      <group scale={0.018}>
        <mesh
          geometry={nodes.Unity_3DLogo_Material_0.geometry}
          material={materials.Material}
          rotation={[-Math.PI / 3.3, 0, 11.8]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/unity.gltf");
