/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\VR\scene.gltf 
Author: VAR Lab (https://sketchfab.com/varlab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oculus-quest-2-headset-with-new-strap-7ecf473077064b2eab5fd20d87a1919f
Title: Oculus Quest 2 Headset (With New Strap)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VR(props) {
  const { nodes, materials } = useGLTF("./models/VR/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={5} position={[-1, 3, 2]} />
      <group rotation={[-Math.PI / 2, 0, 4.3]} scale={0.021}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/VR/scene.gltf");
